services:
  - type: web
    name: weatherwebsite
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: EDIT_PASSWORD
        generateValue: true
